### ISSUE TITLE
Add support for aggregate_rows

### ISSUE THREAD

**Issue by insolite** [05bit/peewee-async#10]
From peewee documentation (http://docs.peewee-orm.com/en/latest/peewee/querying.html#using-aggregate-rows):

``` python
query = (User
         .select(User, Tweet)  # As in the previous example, we select both tables.
         .join(Tweet, JOIN.LEFT_OUTER)
         .order_by(User.username)  # We need to specify an ordering here.
         .aggregate_rows())  # Tell peewee to de-dupe and aggregate results.

for user in query:
    print user.username
    for tweet in user.tweets:
        print '  ', tweet.message
```

Imagine, we have 2 users: "A" and "B". "A" have 1 tweet and "B" have 2 tweets.
The example above would result in something like this:

``` python
A
  tweet1
B
  tweet2
  tweet3
```

Now, I'm trying to implement the same using peewee_async:

``` python
query = yield from peewee_async.execute(
         User
         .select(User, Tweet)  # As in the previous example, we select both tables.
         .join(Tweet, JOIN.LEFT_OUTER)
         .order_by(User.username)  # We need to specify an ordering here.
         .aggregate_rows())  # Tell peewee to de-dupe and aggregate results.

for user in query:
    print user.username
    for tweet in user.tweets:
        print '  ', tweet.message
```

The result is different:

``` python
A
  tweet1
B
  tweet2
B
  tweet3
```

In pure peewee this happens when aggregate_rows() is not used.
Am I doing something wrong or there is no support for aggregate_rows() in peewee_async?

**Comment by rudyryk** [comment]
@insolite Unfortunately, aggregation is not supported at the moment, because it's handled differently inside peewee and I'd want to avoid copy-pasting that code.

**Comment by insolite** [comment]
@rudyryk Any news on this issue? I'd implement it myself locally, even by copy-pasting, cause I really need it. But maybe you already have any better ideas?

**Comment by rudyryk** [comment]
@insolite The main problem with that is it could be difficult to maintain. And also it can interfere with the existing code and introduce new bugs. I think, It would be OK to have it as an experimental feature for the first time, which is not affecting the existing code of affecting minimally.

**Comment by rudyryk** [comment]
Seems like new peewee handles this differently now, there's no aggregate_rows() anymore. And just probably it's already working in new peewee-async.
