### ISSUE TITLE
asyncpg #question

### ISSUE THREAD

**Issue by DennisMatveyev** [05bit/peewee-async#101]
Hi!
Recently, I have stumbled upon interesting article - https://magic.io/blog/asyncpg-1m-rows-from-postgres-to-python/

Questions:
- Whether peewee-async can work with asyncpg driver?
If not - Do you have some plans to implement interfaces for asyncpg?

Thanks!

**Comment by reillysiemens** [comment]
@DennisMatveyev: Not sure if you're still interested, but FWIW, it looks like asyncpg is being considered over in issue #52. You might ask there instead.

**Comment by kalombos** [comment]
Yeah it does not look complicated to add asyncpg pool backend. You can do it on your own. Unfortunately we don't have plans to add the backend yet. We have plans for adding psycopg3 backend  #225
