### ISSUE TITLE
InterfaceError: (0, '')

### ISSUE THREAD

**Issue by ajithkumargangrapu** [05bit/peewee-async#102]
i am trying to insert a records into mysql db ,
i am facing problem with this statement
 # If the last query was unbuffered, make sure it finishes before
InterfaceError: (0, '')
 can anyone help me through this.

thanks 
Ajith

**Comment by fanjindong** [comment]
+1

**Comment by rudyryk** [comment]
Looks like mixing sync and async code here to me, what is `like_user` here in example? And also `item.post` is a sync call (as it is in peewee and we don't provide async for that).
