### ISSUE TITLE
NameError: name 'legacy_table_names' is not defined

### ISSUE THREAD

**Issue by hhstore** [05bit/peewee-async#103]
# when to support `peewee 4.x`?

- when i try to use meta.`legacy_table_names = False` to alter table name.
- then, happened this error.
- so, i check the `peewee` version, find `peewee = 2.10.2`, < `4.x`, not support this field.

```
import peewee

from backend.g import g_db


class BaseModel(peewee.Model):
    created_at = peewee.DateTimeField()
    updated_at = peewee.DateTimeField()

    class Meta:
        database = g_db
        # table_name = ""
        # legacy_table_names = False
        print(f"tb: {legacy_table_names}")

```

**Comment by rudyryk** [comment]
@hhstore Whoa :) peewee 3.0 support is still in alpha and now we get peewee 4.0

**Comment by rudyryk** [comment]
It seems like you've just installed older peewee version, so it's not related to peewee-async, as I can see.
