### ISSUE TITLE
Savepoint incompatible with peewee

### ISSUE THREAD

**Issue by kapucko** [05bit/peewee-async#106]
Hi,

when using transactions -> `async with objects.atomic()` I get the following error:
```
  File "/usr/local/lib/python3.7/site-packages/peewee_async.py", line 1361, in __init__
    self.quoted_sid = db.compiler().quote(self.sid)
AttributeError: 'PostgresqlDatabase' object has no attribute 'compiler'
```
The problem is that the API of `PostgresqlDatabase` was changed and according to peewee implementation it should be: `self.sid.join(self.db.quote)` -> [reference](https://github.com/coleifer/peewee/blob/3.7.1/peewee.py#L3636)

I have prepared PR for this.

Thank you for your great work :)

**Comment by kapucko** [comment]
PR: https://github.com/05bit/peewee-async/pull/107

**Comment by rudyryk** [comment]
@kapucko Thank you! I'll try to check it soon. That's looking good but I'm not sure about what peewee version is required for this to work, maybe we'll need update dependencies too.

**Comment by rudyryk** [comment]
#107 is merged
