### ISSUE TITLE
Bulk insert doesn't return list

### ISSUE THREAD

**Issue by insolite** [05bit/peewee-async#118]
As I see the `insert` function is being used for bulk inserts as well. Therefore this [changes](https://github.com/05bit/peewee-async/pull/97/files#diff-0d5a10a212d3e212e772acf80c3dad61R600) for `peewee>=3` support are breaking the support of list returning for bulk inserts. Shouldn't it just do `fetchall()` instead of `fetchone()[0]`?

**Comment by kalombos** [comment]
It works now. See https://github.com/05bit/peewee-async/blob/e9f85e84a61954f5f2951afb13525dd96832ac59/tests/test_inserting.py#L95 for more information
