### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by chrrfrsv** [05bit/peewee-async#126]
Hello! 

Is there going to be the SQLite support?
There are some projects like https://github.com/jreese/aiosqlite, which can be used to add this functionality

**Comment by Waitrum** [comment]
yeah

**Comment by kalombos** [comment]
Closed as duplicate  of #166

**Comment by kalombos** [comment]
The sqlite support has been [added](https://github.com/05bit/peewee-async/releases/tag/v2.0.0)
