### ISSUE TITLE
peewee_async.count changes query

### ISSUE THREAD

**Issue by alpo** [05bit/peewee-async#130]
When I tried to reuse the same query in Manager.count and then Manager.scalar I figured out that the first call changes the query.
Something like this:
```
objects = Manager(database)
...
query = SomeClass.select().where(lot of conditions)
count = objects.count(query)  expect number, got number
thing = objects.scalar(query)  expect object of SomeClass, got count
```
Are you sure, that your design is sane?

**Comment by rudyryk** [comment]
@alpo this is not by design, I used such code `clone = query.clone()`, seems like it doesn't do job safely or I'm missing something.

**Comment by kalombos** [comment]
Try AioModel.aio_count method it should work like original count in peewee. The count method is deprecated for now
