### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by aherok** [05bit/peewee-async#134]
Hello!

I'm curious if this project will be continued. I'd want to use it although the readme clearly states it is alpha stage and the last commit happened on 10 May 2019 which does not look optimistic.

If not - how can I find a possible production-ready solution to use Peewee in an ASGI framework?

**Comment by mrkovalchuk** [comment]
Good questions. Thinking about it last 5 days.

**Comment by rudyryk** [comment]
Thank you! Let's move discussion there #135 
@mrkovalchuk thanks for PR, #66 was merged
