### ISSUE TITLE
AttributeError: module 'psycopg2' has no attribute 'errors'

### ISSUE THREAD

**Issue by jwattik** [05bit/peewee-async#138]
Import changes in lib psycopg2 

`File "/Users/wattik/QA/python-qa-custom-packages/venv/lib/python3.7/site-packages/peewee_async.py", line 31, in <module>
    IntegrityErrors += (psycopg2.errors.UniqueViolation,)
AttributeError: module 'psycopg2' has no attribute 'errors'`

![image](https://user-images.githubusercontent.com/22703789/79110998-d97ac900-7da5-11ea-83ef-37433e289599.png)

p.s. 
Used 
psycopg2-binary=2.8.5
peewee-async=0.7.0
peewee=3.13.2

**Comment by rudyryk** [comment]
@jwattik thanks for the PR!
