### ISSUE TITLE
AttributeError: 'Model' object has no attribute '_database'

### ISSUE THREAD

**Issue by daeeros** [05bit/peewee-async#140]
Hi, i trying to insert new element in database,

```
class BaseModel(Model):
    class Meta:
        database = database

class ChildrenHouse(BaseModel):
    user_id = IntegerField(primary_key=True)
    chat_id = BigIntegerField()
    registered = DateTimeField(default=datetime.now())

    class Meta:
        indexes = (
            (('user_id', 'chat_id',), True),
        )

await db.execute(ChildrenHouse.create(user_id=target_id, chat_id=msg.receiver_id))
His inserting info i see database, but giving me error, why?
AttributeError: 'ChildrenHouse' object has no attribute '_database'
```

**Comment by ObsidianDestroyer** [comment]
> Hi, i trying to insert new element in database,
> 
> ```
> class BaseModel(Model):
>     class Meta:
>         database = database
> 
> class ChildrenHouse(BaseModel):
>     user_id = IntegerField(primary_key=True)
>     chat_id = BigIntegerField()
>     registered = DateTimeField(default=datetime.now())
> 
>     class Meta:
>         indexes = (
>             (('user_id', 'chat_id',), True),
>         )
> 
> await db.execute(ChildrenHouse.create(user_id=target_id, chat_id=msg.receiver_id))
> His inserting info i see database, but giving me error, why?
> AttributeError: 'ChildrenHouse' object has no attribute '_database'
> ```

How you solved this?

**Comment by rudyryk** [comment]
@ObsidianDestroyer this is wrong usage of `db.execute`.

`ChildrenHouse.create(...)` is already executing sync query and returns `ChildrenHouse` object.
