### ISSUE TITLE
How the hell join() works for table with multiple same FK?

### ISSUE THREAD

**Issue by xplsek03** [05bit/peewee-async#163]
Hey, I have a problem. How am I supposed to do join() with model like this (just a pseudocode):
```
class User():
    ....

class Offer():
    user1 = model.User()
    user2 = model.User()
    user3 = model.User()

off = await appl.execute(Offer.select().join(User, on=(User.id==Offer.user1)))
for o in off:
    print(o.user1)
```
(from [here](https://github.com/05bit/peewee-async/issues/15#issuecomment-257145244))
I tried literally all options but I am still getting: 

```
AssertionError: Error, sync query is not allowed! Call the `.set_allow_sync()` or use the `.allow_sync()` context manager.
500 POST /offers/sgn (::1) 62.84ms
```

**This is working when: I remove user2 and user3 fields, or when not run with tornado unittests (then it works even with user2 and user3 fields).** Maybe it was bad idea to go with async.

**Comment by rudyryk** [comment]
@xplsek03 
> I am going to rewrite everything to motor (mongodb) now

If you decide to go that way, take in consideration that Motor is nothing more that `loop.run_in_executor` https://github.com/mongodb/motor/blob/master/motor/frameworks/tornado/__init__.py#L65 - so it's just using threads. So might be no need to rewrite to Mongo but use `loop.run_in_executor` with sync peewee.

And yes, peewee was not designed with async in mind and dealing with related fields queries is a kind of pain in async approach. The idea is to explicitly construct the query to fetch all needed fields in one request but that's not trivial for general case.

**Comment by xplsek03** [comment]
> @xplsek03
> 
> > I am going to rewrite everything to motor (mongodb) now
> 
> If you decide to go that way, take in consideration that Motor is nothing more that `loop.run_in_executor` https://github.com/mongodb/motor/blob/master/motor/frameworks/tornado/__init__.py#L65 - so it's just using threads. So might be no need to rewrite to Mongo but use `loop.run_in_executor` with sync peewee.
> 
> And yes, peewee was not designed with async in mind and dealing with related fields queries is a kind of pain in async approach. The idea is to explicitly construct the query to fetch all needed fields in one request but that's not trivial for general case.

Oh yes, thanks for note on this. I picked mongo since i have experience with that, but in the light of your note I will likely reconsider. I am just sorry I can't be more use to @kalombos on this, databases are my weak spot and I generally avoid that. Too bad, this looked really good.
