### ISSUE TITLE
_prune_fields bug

### ISSUE THREAD

**Issue by gshmu** [05bit/peewee-async#191]
```
if __name__ == '__main__':
    async def main():
        project = Project(id=1, user_id=1)
        project.user_id = 2
        await db_manager.update(project, only=["user_id"])

    asyncio.run(main())
```
project.user is peewee.ForeignKeyField, this will not update project.user_id

**Comment by rudyryk** [comment]
@gshmu Not sure if this call is correct, as I remember you'd need to specify fields as `only=[Project.user_id]`

**Comment by gshmu** [comment]
@rudyryk  peewee Model._prune_fields `only=["user"]` work well.
