### ISSUE TITLE
Update model without manager

### ISSUE THREAD

**Issue by daeeros** [05bit/peewee-async#197]
It is possible update model without manager? Like this:

```python
class BaseModel(peewee.Model):
    class Meta:
        database = database

class User(BaseModel):
    user_id = peewee.BigIntegerField(primary_key=True, unique=True)
    vip = peewee.BigIntegerField(default=None, null=True)
    sex = peewee.IntegerField(default=None, null=True)
    ban = peewee_ad.BinaryJSONField(default=None, null=True)
    
    
local_user = User(user_id=1)
local_user.sex = 1
await local_user.update() # inserts to database
```

**Comment by kalombos** [comment]
Unfortunately it is not possible for the moment. But it is likely **aio_save** method will be added next releases. It will work like sync [save](https://docs.peewee-orm.com/en/latest/peewee/querying.html#updating-existing-records) method

**Comment by daeeros** [comment]
> Unfortunately it is not possible for the moment. But it is likely **aio_save** method will be added next releases. It will work like sync [save](https://docs.peewee-orm.com/en/latest/peewee/querying.html#updating-existing-records) method

I've temporarily made such an implementation, isn't the code too bad?

```python
class BaseModel(peewee.Model):

    class Meta:
        database = database

    async def _upd(self):
        return await manager.update(self)

    async def _del(self):
        return await manager.delete(self)
 ```

**Comment by kalombos** [comment]
The code is not bad we use similar approach in our projects until model methods from #194 will come
