### ISSUE TITLE
[Suggestion] Allow to send created model in manager.create()

### ISSUE THREAD

**Issue by daeeros** [05bit/peewee-async#199]
It would be very convenient to send an already created model in the same way. An example of implementation of such mechanism processing is below.

```python
    async def create(self, model, **kwargs):
        if inspect.isclass(model):
            inst = model(**kwargs)
        else:
            inst = model

        query = model.insert(**dict(inst.__data__))

        pk = await self.db.execute(query)

        if inst._pk is None:
            inst._pk = pk

        return inst
 ```

**Comment by kalombos** [comment]
Well your approach will not be clear for a programmer in such code:
```python
model = Mymodel(field1=5)
manager.create(model, field=6)
```
What should the code do? Shoud be field 5 or 6 when had been inserted?

**Comment by daeeros** [comment]
> Well your approach will not be clear for a programmer in such code:
> 
> ```python
> model = Mymodel(field=5)
> manager.create(model, field=6)
> ```
> 
> What should the code do? Shoud be field 5 or 6 when had been inserted?

If the model being passed has already been created, the other arguments are ignored. Fields are taken directly from the model class itself.

**Comment by kalombos** [comment]
Yes i understand how you snippet works i mean it is still is not clear for a programmer who is reading the code. It looks like you need [save](https://docs.peewee-orm.com/en/latest/peewee/querying.html#updating-existing-records) method As i said it will likely be added
