### ISSUE TITLE
An example about using peewee-async with Tornado

### ISSUE THREAD

**Issue by anjianshi** [05bit/peewee-async#2]
I spent several hours to find how can peewee-async and Tornado work together.
And finally I got this:
https://gist.github.com/anjianshi/0cfb8bee7d7e8a7dd9c6

It seems working. But is it the right way to use them?
May be you can add an example in documents, to help people that not familiar with asyncio or Tornado?

Thank you!

**Comment by rudyryk** [comment]
Hi @anjianshi! Thank you for the report!

And thank you for the research. That is interesting, I didn't tested it that way. And if it's working, then it's probably ok! :) I haven't seen docs about direct support of `yield from` for `tornago.gen.coroutine`, seems like that is implementation specific or just undocumented feature.

Usually I use approach like that:
https://github.com/rudyryk/python-samples/blob/master/hello_tornado/hello_asyncio.py

It's a bit more complex, but we have 'pure' asyncio coroutine methods and thus we're able to use any of asyncio powered libraries within Tornado handlers.

I will add some examples to docs, that is a good idea!

**Comment by anjianshi** [comment]
After several attempts, I think it works, 
Here's my code:
```python
from tornado.platform.asyncio import AsyncIOMainLoop
from tornado.web import RequestHandler
import tornado.gen
import tornado.httpclient
import aiohttp


class TestHandler(tornado.web.RequestHandler):
    @tornado.gen.coroutine
    def get(self):
        total_length = 0
        i = 1
        sites = [
            "http://www.google.com",
            "http://www.twitter.com",
            "http://www.facebook.com"
        ]

        for site in sites:
            resp = yield from aiohttp.request("GET", site)
            body = yield from resp.read()
            total_length += len(body)
            print("site {}, complete".format(i))
            i += 1

        client = tornado.httpclient.AsyncHTTPClient()
        for site in sites:
            resp = yield client.fetch(site)
            total_length += len(resp.body)
            print("site {}, complete".format(i))
            i += 1

        self.write("total length: {}\n".format(total_length))


class Test2Handler(tornado.web.RequestHandler):
    def get(self):
        print("test2 run")
        self.write("test2 run\n")


AsyncIOMainLoop().install()
application = tornado.web.Application([
    (r"/test", TestHandler),
    (r"/test2", Test2Handler)
])
application.listen(port=8888)
asyncio.get_event_loop().run_forever()
```

I open two terminal, and request these url in same time:
```bash
# terminal 1
curl http://localhost:8888/test

# terminal 2
curl http://localhost:8888/test2
```
The app print this:
```
site 1, complete
test2 run
test2 run
test2 run
site 2, complete
test2 run
test2 run
site 3, complete
test2 run
site 4, complete
test2 run
test2 run
site 5, complete
test2 run
site 6, complete
```

Here's some describe in Tornado's document:
<http://tornado.readthedocs.org/en/latest/gen.html>
> If the singledispatch library is available (standard in Python 3.4, available via the singledispatch package on older versions), additional types of objects may be yielded. Tornado includes support for asyncio.Future and Twisted’s Deferred class when tornado.platform.asyncio and tornado.platform.twisted are imported. See the convert_yielded function to extend this mechanism.

**Comment by rudyryk** [comment]
Aha! Seems like this is new feature, from the same page:

> Changed in version 4.1: Support added for yielding asyncio Futures and Twisted Deferreds via singledispatch.

Well, that's great! This is one more step towards unified asynchronous coding approach in Python :)

**Comment by anjianshi** [comment]
:)

**Comment by anjianshi** [comment]
Thanks again!

**Comment by msean** [comment]
I intend to deploy my project on tornado and look for a suitable async  lib for postgresql,I have read some  of your document and I have nerver use peewee before, I have a question, if there is a API for original database SQL query when the API  can not meet the needs of my query...
