### ISSUE TITLE
Refactor Database fetch_results method

### ISSUE THREAD

**Issue by kalombos** [05bit/peewee-async#219]
В AsyncDatabase не должно быть метода fetch_results, логика должна быть перенесена в соответствующие Query-классы: ModelCompoundSelectQuery, RawQuery. Кстати, нужно проверить, есть ли на них тесты, насколько помню тестов на ModelCompoundSelectQuery не было.

> There should not be a fetch_results method in AsyncDatabase. The logic should be transferred to the corresponding Query classes: ModelCompoundSelectQuery, RawQuery. By the way, you need to check if there are tests for them; as far as I remember, there were no tests for ModelCompoundSelectQuery.

 #237 #236

**Comment by rudyryk** [comment]
`Manager` extracted to compatibility module in PR #232

Seems like `AsyncDatabase.fetch_results` might be safely removed, it actually never gets called in tests, check #233
