### ISSUE TITLE
Split code by files

### ISSUE THREAD

**Issue by kalombos** [05bit/peewee-async#223]
Нужно вынести части кода в отдельные файлы. Удобнее делать это в несколько итераций, т.к. на данный момент при установке пакет в корень директории с модулями копируются файлы peewee_async.py peewee_asyncext.py Нужно завести директорию peewee-async и перенести в неё peewee_async.py сохранив импорты, также смотри #222

>It is necessary to move parts of the code into separate files. It is more convenient to do this in several iterations, because At the moment, when installing the package, the peewee_async.py files peewee_asyncext.py are copied to the root of the directory with modules. You need to create a peewee-async directory and move peewee_async.py to it, saving the imports, also see #222

**Comment by rudyryk** [comment]
I suggest to stick with a single `peewee_async.py` for main implementation.

Not because I dislike modules but because peewee itself is a single peewee.py and it contains much-much more complexity. Being one-file ORM is a spirit of the initial project, and I'd love to follow that.

But what we could to for cleanups it to extract legacy / deprecated modules into `peewee_async_compat` and just import what we need in peewee_async.py. That would emphasize what is stable core and what is just an old / compatibility layer.

**Comment by rudyryk** [comment]
`Manager` extracted to compatibility module in PR #232

**Comment by kalombos** [comment]
Yeah I know about single peewee.py and i remember how 6-8 years ago my computer slowed down when i opened the file :)This happened because the IDE did not have enough resources to parse a file of 10 thousand lines. And it may lead to [cyclic imports](https://github.com/05bit/peewee-async/pull/232/files#diff-6d8e1a719b427648df69db4eabd199c476949bc7b953ad88e6bcef1619d209e4R52) and this may lead to import hell :) Also i am worried about that we put all our files(peewee_async, *_compat, *_ext) in the root of the python package directory. It seems no big deal at the moment but you know the Murphy's law... :) Some day somebody will create local peewee_compat file and lose couple of hours in debugging. So i think encapsulate our package at first is not a bad idea :) Splitting also could be helpful for typing #224 to make the process iterative.

All i am trying to say the spirit of peewee is not for free we should pay for it(our time). Do we really need this?

**Comment by rudyryk** [comment]
> Some day somebody will create local peewee_compat file and lose couple of hours in debugging.

Fair point :) OK, let's split it then.
