### ISSUE TITLE
Add typing

### ISSUE THREAD

**Issue by kalombos** [05bit/peewee-async#224]
Нужно добавить типизацию, также добавить линтер на проверку типизации в ci Удобно делать типизацию итерационно, по файлам, после  #223 

>It needs to add typing, also add a linter to check typing in ci. It is convenient to do typing iteratively, by files, after #223

**Comment by rudyryk** [comment]
This would be great! And as typing is not forced we are not forced to make linter 100% happy from the start, so it can perfectly work with a single file and incomlete annotations as well. We'll just gradually work on linter complaints.
