### ISSUE TITLE
Move manager methods to database

### ISSUE THREAD

**Issue by kalombos** [05bit/peewee-async#229]
Нужно перенести все методы manager-а в класс Database. Все методы в database должны быть асинхронными версиями соответсвующих методов в peewee. По возможности функционал методов должен быть таким же как у синхронных версий. Manager нужно пометить как deprecated

**Comment by rudyryk** [comment]
`Manager` extracted to compatibility module in PR #232

**Comment by kalombos** [comment]
Done
