### ISSUE TITLE
Additional loop support

### ISSUE THREAD

**Issue by kalombos** [05bit/peewee-async#230]
В процессе рефакторинга была удалена возможность передавать event-loop как параметр. Этот параметр использовался для определения текущего таска в функции asyncio.current_task А также в методах create_pool для создания пула. Нужно ли вернуть поддержку дополнительного even-loop-а? Для каких кейсов это может быть использовано?

**Comment by spumer** [comment]
It's approach is used in earlier versions of asyncio. After ~3.7 it's replaced by `asyncio.get_running_loop` and manually passing loop is deprecated in high-level API.

**Comment by spumer** [comment]
My suggestion is use `asyncio.get_running_loop()` in places where `loop` object is required

**Comment by kalombos** [comment]
Oh, i get it thank you @spumer aiomysql and aiopg run get_running_loop() by default and i suggest contextvar can detect the running loop either. Seems like removing loop is ok and the issue can be closed
