### ISSUE TITLE
Add compound query support for AioModel

### ISSUE THREAD

**Issue by kalombos** [05bit/peewee-async#237]
This code should work:

```python
query = (
    TestModel.select().where(TestModel.id == obj1.id) |
    TestModel.select().where(TestModel.id == obj2.id)
)
await query.aio_execute()
```

**Comment by spumer** [comment]
This is really correct query for Peeweee? D:

**Comment by kalombos** [comment]
Yeah. [Here](https://github.com/05bit/peewee-async/blob/master/tests/compat/test_compat.py#L19) is an example. The issue is about backward compatibility mostly since the query works if you use manager. The problem is there are a lot of cases for contstructing such queries. [Here](https://github.com/coleifer/peewee/blob/master/peewee.py#L7257) is and [here](https://github.com/coleifer/peewee/blob/master/peewee.py#L2253) is and [here](https://github.com/coleifer/peewee/blob/master/peewee.py#L1154) is. I think fixing the query is enough for first iteration :)
