### ISSUE TITLE
Found a get_or_none bug

### ISSUE THREAD

**Issue by suhongrui** [05bit/peewee-async#245]
```python

async def get_or_none(self, model_, *args, **kwargs):
    """Try to get an object and return None if it doesn't exist."""
    try:
        return (await self.get(model_, *args, **kwargs))
    except model_.DoesNotExist:
        pass

query = User.select().filter(User.id == 1000000).limit(1)
user = await db.get_or_none(query)

```
When model_ is peewee.Query, an exception will occur if no data can be queried because AttributeError: 'ModelSelect' object has no attribute 'DoesNotExist'
Maybe it should be changed to:
```python
     async def get_or_none(self, model_, *args, **kwargs):
         """Try to get an object and return None if it doesn't exist."""
         if isinstance(model_, peewee.Query):
             model = model_.model
         else:
             model = model_
         try:
             return await self.get(model_, *args, **kwargs)
         except model.DoesNotExist:
             pass

```

**Comment by kalombos** [comment]
This api is deprecated could you switch and try [this one](https://peewee-async-lib.readthedocs.io/en/latest/peewee_async/api.html#peewee_async.AioModel.aio_get_or_none) instead? Will it work for you case?

**Comment by suhongrui** [comment]
> This api is deprecated could you switch and try [this one](https://peewee-async-lib.readthedocs.io/en/latest/peewee_async/api.html#peewee_async.AioModel.aio_get_or_none) instead? Will it work for you case?

Thank you for your reply. I tested it according to your method and it solved my problem perfectly.

Also, if you want to achieve master-slave reading and writing separation, do you have any recommended methods?

**Comment by kalombos** [comment]
Your example raises an error for me. Why wouldn't you just use  
```python 
await User.aio_get_or_none(User.id == 4)
``` 
You don't need **limit** statement since you use **aio_get_or_none** shortcut.

**Comment by suhongrui** [comment]
> Your example raises an error for me. Why wouldn't you just use
In a special case, I want to execute the for update statement through get_or_none, so I must use peewee.Query as a parameter.

Hope for a new version in the future:
Can support direct use of peewee.Query in get_or_none.

In addition, I have not found the configuration and method of reading and writing the master-slave library. I hope I can give use cases.

**Comment by kalombos** [comment]
> In a special case, I want to execute the for update statement through get_or_none, so I must use peewee.Query as a parameter.
I doubt it will happen. peewee-async follows the [peewee](http://docs.peewee-orm.com/en/latest/) style and provides [the same api](http://docs.peewee-orm.com/en/latest/peewee/api.html#Model.get_or_none) but with aio prefix. You can pass to query or filter params everything you want that will work. See [the code](https://github.com/05bit/peewee-async/blob/master/peewee_async.py#L772) for more information.

> In addition, I have not found the configuration and method of reading and writing the master-slave library. I hope I can give use cases.

Sorry i don't know what is the master-slave library. Could you explain or provide an example?

**Comment by suhongrui** [comment]
> Sorry i don't know what is the master-slave library. Could you explain or provide an example?
There are two database servers, one for reading data and one for writing data.

**Comment by kalombos** [comment]
> There are two database servers, one for reading data and one for writing data.

You can use 2 [database](https://peewee-async.readthedocs.io/en/latest/peewee_async/api.html#peewee_async.PooledPostgresqlDatabase)  instances. Also you can use 2 [manager](https://peewee-async.readthedocs.io/en/latest/peewee_async/api.html#peewee_async.Manager) instances instead but it is deprecated and will be removed
