### ISSUE TITLE
Cursor never released for MySQLDatabase

### ISSUE THREAD

**Issue by spumer** [05bit/peewee-async#26]
When we bind `cursor.release` function in AsyncMysqlConnection class we expect this is not a coroutine.

```python
def release():
    cursor.close()
    self.pool.release(conn)
cursor.release = release

# OR 

cursor.release = lambda: cursor.close()

```

`aiomysql.cursors.Cursor.close` defined like a coroutine: https://github.com/aio-libs/aiomysql/blob/master/aiomysql/cursors.py#L151

So, for solve this issue we can detour `.close()`:

```python
def release():
    self.loop.call_soon(cursor.close())
    self.pool.release(conn)
cursor.release = release

# OR 

cursor.release = lambda: self.loop.call_soon(cursor.close())
```

or we can return Future: by `asyncio.async(cursor.close())`
This will guarantees execution and allow `yielding from`.

I preffer first solution. Let's talk about that. Можно на нашем :)

**Comment by rudyryk** [comment]
Спасибо :) I get an idea how to fix it, will try today. And another important issue is to have a test case for that.

**Comment by rudyryk** [comment]
@spumer Заработало? :)
