### ISSUE TITLE
Remove AsyncQueryWrapper

### ISSUE THREAD

**Issue by kalombos** [05bit/peewee-async#276]
The AsyncQueryWrapper class seems redundant. Its only function at the moment is the ability not to immediately convert data from the cursor into models, but only when iterating over the class. It’s very difficult to come up with a case for using such an opportunity, and it doesn’t save a lot of resources. Perhaps the class was intended to work with a cursor, its fetchone and fetchall functions. With the current architecture this is also difficult

I think some function like that would be enough
```python
def fechall():
    sync_cursor = SyncCursorAdaper.from_cursor(cursor) #  RowsCursor renamed to SyncCursorAdapter
    _result_wrapper = query._get_cursor_wrapper(sync_cursor)
    return list(_result_wrapper)
```
Perhaps in the future this function will expand into a class similar to AsyncQueryWrapper, but it will only be needed for internal use. External results will always be as list of models.

@rudyryk what do you think?

**Comment by rudyryk** [comment]
@kalombos I think it's OK to remove/replace it, as it never was a part of documented interface. Historically I was trying to mimic original's `peewee` where possible to make it easier to convert the logic.

**Comment by kalombos** [comment]
@gshmu you wrote:

> I want support iter_models, aio fetch row from db one by one.

Do you mean iterate over the AsyncQueryWrapper and call cursor.fetchone() on each iteration and then convert the string to a model? It didn’t work like that before, fetchall was always called immediately, _result_cache was filled, and as it was iterated, the string was simply converted into a model. Which was unnecessary. With the current architecture, pagination on cursors is difficult, since the connection must be returned to the pool and it is not clear when to return it. In addition, this could potentially lead to connections ending. You can control the cursor yourself, just use 

```python 
AioDatabase.aio_execute(query=YourQuery, fetch_results=your_function_with_cursor_pagination)
```

**Comment by gshmu** [comment]
my iter row code here, and it work well. 
```
    async def iter(self, query):
        query = self._swap_database(query)
        cursor = await peewee_async._execute_query_async(query)

        result = peewee_async.AsyncQueryWrapper(cursor=cursor, query=query)
        wrapper = result._result_wrapper
        if not wrapper.initialized:
            wrapper.initialize()  # Lazy initialization.
            wrapper.initialized = True
        try:
            while True:
                row = await cursor.fetchone()
                if not row:
                    raise GeneratorExit
                yield wrapper.process_row(row)
        except GeneratorExit:
            pass
        finally:
            await cursor.release()
```

**Comment by kalombos** [comment]
As i understand by using cursor pagination you don't want to load all models from your table to memory as list? You can just use limit statement in your query. Or you can do something like this in next released version:

```
def get_wrapper_with_empty_rows(cursor: CursorProtocol):
    sync_cursor = SyncCursorAdapter([], cursor.description)
    return query._get_cursor_wrapper(sync_cursor)


async def fetch_with_cursor_pagiantion(cursor: CursorProtocol, query: BaseQuery) -> List[Any]:
    wrapper = get_wrapper_with_empty_rows(cursor)
    try:
        while True:
            row = await cursor.fetchone()
            if not row:
                raise GeneratorExit
            # yield wrapper.process_row(row) # Unfortunately you cant yield here
            your_model_object = wrapper.process_row(row)
            handle(your_model_object)
    except GeneratorExit:
        pass
    # finally:
    #     await cursor.release() # released automatically

async def iter(query):
    fetch_results = partial(fetch_with_cursor_pagiantion, query=query)

    await db.aio_execute(query, fetch_results=fetch_results)

We need a solution how to work with cursor pagination in the current architecture since cursor and connection released automatically after each query. We will find it likely later
