### ISSUE TITLE
get row_sql data

### ISSUE THREAD

**Issue by ipfred** [05bit/peewee-async#289]
sql1 = f"SELECT  * from task order by task_start_time limit 1"
all_objs = await TaskVpInfo.raw(sql1).aio_execute()
for obj in all_objs:
    print(obj)

I want to use the native SQL query results, how to get the result? OBJ = None output this code .this query should select data

**Comment by kalombos** [comment]
[Here](https://github.com/05bit/peewee-async/blob/master/tests/aio_model/test_selecting.py#L22) is an example
Or use just use a [connection](https://github.com/05bit/peewee-async/blob/master/tests/test_database.py#L16) if you don't need a model at all
