### ISSUE TITLE
Manager class

### ISSUE THREAD

**Issue by MumukoQAQ** [05bit/peewee-async#299]
Is the Manager class deprecated in the latest version?

**Comment by kalombos** [comment]
It's removed in 1.0.0

**Comment by MumukoQAQ** [comment]
> It's removed in 1.0.0

Thank，What's the alternative? I don't see this document update at [High-level (new) API]( https://peewee-async.readthedocs.io/en/latest/peewee_async/api.html)

**Comment by kalombos** [comment]
It's deprecated documentation. Here is the new [one](https://peewee-async-lib.readthedocs.io/en/latest/) @rudyryk btw could you drop the old documentation hosting? I have been worried people will be confused.
