### ISSUE TITLE
Playhouse support

### ISSUE THREAD

**Issue by horpto** [05bit/peewee-async#3]
Now peewee_async.PostgresqlDatabase inherits from peewee.PostgresqlDatabase so we cannot use async-peewee and playhouse extensions for PostgreSql (it requires PostgresqlExtDatabase from playhouse.postgres_ext) together.

**Comment by rudyryk** [comment]
@horpto I'll reopen this issue, as It still needs clear solution :)

As I see [aiopg](https://github.com/aio-libs/aiopg) library has support for both `hstore` and `json` features out of box, and all we need is pass connection parameters. This needs to be documented and tested, and code by itself should be just a little bit adjusted.

**Comment by rudyryk** [comment]
Oh, we'll still need factory method for providing field overrides to generate proper SQL with JSON and Hstore fields support. Anyway, current code doesn't take care of it when creating async connection, but it should!

**Comment by rudyryk** [comment]
@horpto Please take a look at new [peewee_asyncext](https://github.com/05bit/peewee-async/blob/master/peewee_asyncext.py) module. Tests are passing, docs need to be updated.

**Comment by horpto** [comment]
@rudyryk I glanced at the module and it's good work in my view. There are 4 similar classes instead of 2 or even 1 generic classes, is it ok? I mean I tried to avoid reasonless growth of classes and save interfaces as possibly.

What do you assumes by "roviding field overrides to generate proper SQL with JSON and Hstore fields support"? I don't understand that.

**Comment by rudyryk** [comment]
Docs are updated: http://peewee-async.readthedocs.org/en/latest/peewee_async/api.html

I think that mimics original peewee's hierarchy is cleaner was, it will be easier to migrate code from sync to async when needed.
