### ISSUE TITLE
Unable to use Proxy database

### ISSUE THREAD

**Issue by dgelvin** [05bit/peewee-async#30]
I'm still running into issues trying to wrap the `Manager` around a peewee `Proxy`.  I've created a repo that shows my use case here:

https://github.com/dgelvin/peewee-async-test

I am using [asynctest ](https://github.com/Martiusweb/asynctest) which uses a new event loop for each test to ensure that tests are completely independent.

**Comment by dgelvin** [comment]
Thanks- I appreciate it.

**Comment by rudyryk** [comment]
You're welcome.
