### ISSUE TITLE
Transaction with aio_get does not work

### ISSUE THREAD

**Issue by usernamecrypt125** [05bit/peewee-async#306]
If you use according to the documentation immediately update or select, the transaction works. If you use aio_get at once, the transaction does not work
```
async with database.aio_atomic():
    history: History = await History.aio_get(History.id == 50111)
```

**Comment by kalombos** [comment]
```python
    async with db.aio_atomic():
        result = await TestModel.aio_get(TestModel.id == obj1.id)
```
Well i have just tested this code and it produced next sql code:

```
postgres-1  | 2024-12-15 06:47:17.555 UTC [416] LOG:  statement: BEGIN
postgres-1  | 2024-12-15 06:47:17.556 UTC [416] LOG:  statement: SELECT "t1"."id", "t1"."text", "t1"."data" FROM "testmodel" AS "t1" WHERE ("t1"."id" = 147) LIMIT 1 OFFSET 0
postgres-1  | 2024-12-15 06:47:17.556 UTC [416] LOG:  statement: COMMIT

```
All works fine. And why do you need SELECT statement in trasaction?

**Comment by usernamecrypt125** [comment]
> All works fine. And why do you need SELECT statement in trasaction?

1) It's about a race of states. To avoid using Semaphore or Lock from the asyncio library. We need to make it clear
2) Let's imagine a payment from a store was received by mistake twice - it is necessary to check in the history table whether this payment is not received for the second time at record 70771.

```
async with database.aio_atomic():
        history: History = await History.aio_get(History.id == 70771)
        if history.status != 'paid':
            history.status = 'paid'
            user.balance += amount
            await history.aio_save()
        else:
            logger.error(f'payment: {history.id} paid!!!')
            return
```

The code above may execute twice due to a state race because the ISOLATION_LEVEL_READ_COMMITTED transaction has failed

**Comment by kalombos** [comment]
You should use SELECT FOR UPDATE instead of aio_get to avoid race condition.

**Comment by usernamecrypt125** [comment]
> You should use SELECT FOR UPDATE instead of aio_get to avoid race condition.

I understand. But shouldn't aio_atomic have that by default?

**Comment by kalombos** [comment]
You mean aio_get should fire SELECT FOR UPDATE if it'is under aio_atomic? Well it is definitely not a bug but possible feature :) I don't think it is a good idea. What if i don't want to lock a record under transaction for some query? if there is a lock it's better to write clear code like  ```await History.select().where(History.id == 70771).for_update().aio_execute()``` instead of using implicit **select for update** under aio_get.

**Comment by usernamecrypt125** [comment]
> You mean aio_get should fire SELECT FOR UPDATE if it'is under aio_atomic? Well it is definitely not a bug but possible feature :) I don't think it is a good idea. What if i don't want to lock a record under transaction for some query? if there is a lock it's better to write clear code like `await History.select().where(History.id == 70771).for_update().aio_execute()` instead of using implicit **select for update** under aio_get.

Yes. So what's the difference between your request and mine? No difference, but one query has a transaction and the other doesn't.

**Comment by usernamecrypt125** [comment]
This hidden problem
A week ago, due to a race of states, the client's balance was replenished twice, only to find out later that aio_get does not block the entry.
