### ISSUE TITLE
Question - peewee-async & tornado & py.test

### ISSUE THREAD

**Issue by juntatalor** [05bit/peewee-async#33]
Hi! I'm trying to configure testing for my tornado web application with py.test and awesome peewee-async.
When I run application generally - everything is ok.
The problem is that I get my tests stuck and then fail with AssertionError: Async operation timed out after 5 seconds. I think that peewee async run on 
I take code from https://github.com/05bit/peewee-async/blob/master/examples/tornado_sample.py, and remove the loop.run_forever().

Than try something like (with https://pypi.python.org/pypi/pytest-tornado):

```
from tornado_sample import app as application
import pytest

@pytest.fixture
def app():
    return application

@pytest.mark.gen_test
def test_hello_world(http_client, base_url):
    response = yield http_client.fetch(base_url + '?id=1')
    assert response.code == 200
```

And it fails on timeout.

I tried to reassign application.objects in app fixture. Tried to use tornado AsyncHTTPTestCase. Nothing helps - the await self.application.objects.get(TestNameModel, id=obj_id) (and any other query) never ends. I think, that the problem is in running query on stopped (or not launched) io loop.
Standart torando testing (AsyncHTTPTestCase) fails too.
Also, i tried to run tests using https://pypi.python.org/pypi/pytest-asyncio. It works (not very convenient - all calls to AsyncHTTPClient.fetch() should be bridged with http://www.tornadoweb.org/en/stable/asyncio.html#tornado.platform.asyncio.to_asyncio_future), but event loop closes after first test, and i did not find the way to start it.
Could you please provide the working testable sample?

**Comment by rudyryk** [comment]
> Async operation timed out after 5 seconds

That usually means event loop mismatching, e.g. running loop is not set as the current event loop. I don't know how to handle this correctly with pytest, but the idea is that you should either pass loop instance explicitly or call `asyncio.set_event_loop(loop)` before running the loop.

**Comment by rudyryk** [comment]
@juntatalor Could you please provide your non-working code sample?

**Comment by rudyryk** [comment]
@juntatalor This works for me:

```python
import asyncio
import pytest
from tornado_sample import app as application
from tornado.ioloop import IOLoop

IOLoop.configure('tornado.platform.asyncio.AsyncIOMainLoop')

@pytest.fixture
def app():
    # Not sure if we need to explicitly set up the current event lopp
    # Test sample works fine with or without these lines
    # loop = IOLoop.current().asyncio_loop
    # asyncio.set_event_loop(loop)
    return application

@pytest.mark.gen_test
def test_hello_world(http_client, base_url):
    response = yield http_client.fetch(base_url + '?id=1')
    assert response.code == 200

@pytest.mark.gen_test
def test_hello_world_2(http_client, base_url):
    response = yield http_client.fetch(base_url + '?id=2')
    assert response.code == 200

@pytest.mark.gen_test
def test_hello_world_3(http_client, base_url):
    response = yield http_client.fetch(base_url + '?id=3')
    assert response.code == 200
```

**Comment by juntatalor** [comment]
@rudyryk 
Thanks.
The problem was in my
`AsyncIOMainLoop().install()`
I changed to
`IOLoop.configure('tornado.platform.asyncio.AsyncIOMainLoop')`
And that solved the problem.
