### ISSUE TITLE
Create data dynamically happened error...

### ISSUE THREAD

**Issue by msean** [05bit/peewee-async#43]
I create a Model below
```
class Student(peewee.Model):
    score = peewee.IntegerField()
    name = peewee.CharField(max_length=64,  null=True)
    class Meta:
        database = DATABASE
        db_table = 'student'
        schema = 'biz'
```
when I create a data with the usual method:
```
_create_sql = {
            'name':'jack',
            'score':75,
        }
 yield from self.db.create(Student,**_create_sql)
```
It worked fine actually.But when I create the data in a dynamic way like this:
```
_create_sql = {
            'name':'jack',
            'score':75,
        }
 yield from exec('%s.create(%s,**%s)'%(self.db,Student,_create_sql))
```
It happened a error:
```
  File "<string>", line 1
        yield from <peewee_async.Manager object at 0x7f1728e74da0>.create(<class 'models.Student'>,**{'name': 'jack', 'score': 75})
                   ^
    SyntaxError: invalid syntax

```
How can I solve the problem?

**Comment by rudyryk** [comment]
@msean Seems like something wrong with Python syntax here, not sure it's somehow related to the lib. And I'm not sure what you you want to achieve and why using `exec()` at all? Anyway, I see some kind if misuse of `exec()` here.

As I don't see any issue with the lib, closing this one.

**Comment by msean** [comment]
OK,Thank you,just for the need of some common interface..
