### ISSUE TITLE
Event loop is closed & 'playhouse._speedups._ModelQueryResultWrapper' object has no attribute 'initialize'

### ISSUE THREAD

**Issue by sh0uw4ng** [05bit/peewee-async#48]
code:
```
import asyncio
import peewee
import peewee_async

database = peewee_async.**PooledMySQLDatabase**('test')

class TestModel(peewee.Model):
    text = peewee.CharField()

    class Meta:
        database = database

TestModel.create_table(True)
TestModel.create(text="Yo, I can do it sync!")
database.close()

objects = peewee_async.Manager(database)
database.set_allow_sync(False)

async def handler():
    await objects.create(TestModel, text="Not bad. Watch this, I'm async!")
    all_objects = await objects.execute(TestModel.select())
    for obj in all_objects:
        print(obj.text)

loop = asyncio.get_event_loop()
loop.run_until_complete(handler())
loop.close()

with objects.allow_sync():
    TestModel.drop_table(True)
```

### Win7
- python35
- peewee-2.8.5
- peewee-async-0.5.6

> RuntimeError: Event loop is closed

![image](https://cloud.githubusercontent.com/assets/8855832/20788417/b064062c-b7eb-11e6-842f-959ede34af74.png)

### Ubuntu16.04
- python35
- peewee-2.8.5
- peewee-async-0.5.6

> AttributeError: 'playhouse._speedups._ModelQueryResultWrapper' object has no attribute 'initialize'
![image](https://cloud.githubusercontent.com/assets/8855832/20788718/d9e56378-b7ec-11e6-8193-63ab610bdca3.png)

**Comment by rudyryk** [comment]
Hmm, that's strange because `peewee-async` should not use `playhouse._speedups. _ModelQueryResultWrapper ` (it's incompatible)

**Comment by rudyryk** [comment]
Ah, I see - speedups are disabled for Postgresql, but not for MySql, this should be fixed. As a workaround you may manually disable speedups:

```
database = peewee_async.PooledMySQLDatabase('test', use_speedups=False)
```

**Comment by sh0uw4ng** [comment]
@rudyryk Thanks a lot. It's works.
