### ISSUE TITLE
Add example for tornado

### ISSUE THREAD

**Issue by horpto** [05bit/peewee-async#5]
Hi, I saw yor comment on stackoverflow.com about supporting tornado framework on asyncio loop. Could you add simple example for working with peewee_async on tornado framework?

**Comment by rudyryk** [comment]
@horpto Sure, I'll find some time to refine docs :)

You can find some sample here:
https://github.com/05bit/peewee-async/issues/2#issuecomment-96162737

But I prefer to using explicit `asyncio` wrapper for Tornado handlers like that:
https://github.com/rudyryk/python-samples/blob/master/hello_tornado/hello_asyncio.py

**Comment by rudyryk** [comment]
@horpto So, actually after adding support via wrapper you just write pure `asyncio` methods.

**Comment by rudyryk** [comment]
http://peewee-async.readthedocs.org/en/latest/peewee_async/examples.html#using-with-tornado

**Comment by horpto** [comment]
@rudyryk thanks
