### ISSUE TITLE
Support Models without specified database

### ISSUE THREAD

**Issue by IlyaSemenov** [05bit/peewee-async#51]
Currently when you define a model and don't define the `database` meta on models (but still pass the proper database instance to `peewee_async.Manager`), peewee-async crashes when executing a query:

```python
"Error, models's database and manager's are different: %s" % model
```

This can be hacked around like this (assuming the database is postgres):

```python
class MyModel(peewee.Model):
    class Meta:
        # peewee-async insists on "compatible" database
        database = peewee.PostgresqlDatabase(None)
```

But why the limitation in the first place? I understand that if the model database meta **was** specified and it **was** different from what is then passed to `peewee_async.Manager`, the compatibility check would make sense. But if a user will never use the non-async way, and never specified the database meta, this check is not needed. Please remove it for that case.

Having the "global" database object is an anti-pattern anyway.

**Comment by rudyryk** [comment]
@IlyaSemenov Probably it's changed in newer peewee but as far as I know some queries are (was?) constructed against specific database even before execution. So I decided to follow the rule "Errors should never pass silently" and failing fast.

**Comment by rudyryk** [comment]
@IlyaSemenov So is it possible that `query.database` is `None`? Should the checking be like that?

```python
if not query.database or (query.database == self.database):
    return query
```

Colud you please provide some more details? A test case or just an example would be useful.

**Comment by rudyryk** [comment]
@IlyaSemenov I see, thank you!

But I just don't understand, how peewee would compile SQL query without `_meta.database`? It's extensively used in `peewee.Query` class and it depends on database engine, e.g. SQL for sqlite is different from one for PostgreSql etc.

**Comment by rudyryk** [comment]
@IlyaSemenov Actually if you omit `Meta.database` then peewee will internally fallback to default `SqliteDatabase('test')` as I remember. So all queries will be compiled against sqlite in that case.

**Comment by IlyaSemenov** [comment]
I agree, that makes sense. Moreover, providing an un-initialized database is one of the methods [recommended by Peewee](http://docs.peewee-orm.com/en/latest/peewee/database.html#run-time-database-configuration). Let's keep it as is.
