### ISSUE TITLE
Joins by back refs does not working

### ISSUE THREAD

**Issue by dyus** [05bit/peewee-async#62]
I try to make query like this
```python
query = ItemModel.select(ItemModel, ManyToManyItemModel)
        .join(VideoItemScreenshotModel, JOIN.LEFT_OUTER,
              on=(ItemModel.id == ManyToManyItemModel.item_id)
              .alias('m2m_item_set')).aggregate_rows()
```
I expected to have results list of objects at `m2m_item_set` and i have it if i call this synchronously.
But when i call it async for example `await ItemModel.db_manager.execute(query)` i'v got `ManyToManyItemModel` in the `m2m_item_set`. Am I doing something wrong? 
I understand how joined data adds in peewee and i did not find code which should do this in peewee_async. 
In peewee https://github.com/coleifer/peewee/blob/master/peewee.py#L2720 this place do exactly what i want.
I can provide small app for showing the problem if you interested in.

**Comment by rudyryk** [comment]
@dyus Yes, there's no support for aggregated queries in `peewee-async` yet.  This is tricky part and seems that we need to re-implement it in async manner to have it.

**Comment by rudyryk** [comment]
As I can see, there's no more aggregate_rows() in peewee 3.0+
