### ISSUE TITLE
aiopg/aiomysql as optional dependecies

### ISSUE THREAD

**Issue by bmlis** [05bit/peewee-async#63]
Right now when installing peewee-async, aiopg/aiomysql has to be added as my project dependency, which can be confusing. I have to wonder if someone added it and forgot to use it or some external (peewee-async) lib uses it. I would expect I can just:
```
install_requires=[
        'peewee-async[aiopg]==0.5.7',
],
```
which I feel is the correct way to go with optional dependencies.

**Comment by rudyryk** [comment]
Thank you @bmlis, sounds reasonable, I'll add such dependencies for convince.
