### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by Akay7** [05bit/peewee-async#65]
I would like make few bulk insert at same time. Can I do that with peewee-async?

**Comment by ehajri** [comment]
I'd like that, too.

**Comment by rudyryk** [comment]
It should be possible by creating insert query and running with `execute()`:

```
bulk_insert = MyModel.insert_many(row_dicts)
await objects.execute(bulk_insert)
```

Did you test that?

**Comment by mrkiril** [comment]
@rudyryk 

as I know `bulk_insert = MyModel.insert_many(row_dicts)` create and execute query in the same time.
I try to use it with peewee-async and get the duplicate row in db/

if U know good way to use it, pls tell

**Comment by kalombos** [comment]
@mrkiril it does not. See https://docs.peewee-orm.com/en/latest/peewee/api.html#Model.insert_many for example. You should run execute() after insert_many to fire a query
