### ISSUE TITLE
Insert doesn't return the UUID primary key from the database

### ISSUE THREAD

**Issue by captaingarbonza** [05bit/peewee-async#7]
Hi, I'm using peewee_async in a project where the primary ID (a non auto-incrementing UUID) is initialized by the database. If I use the synchronous insert function then the insert is performed and the return value is the id of the inserted row but using the asynchronous calls the insert works but the id comes back as None. This means the return value of create_object is also None.

**Comment by rudyryk** [comment]
Hi @captaingarbonza! Seems like some glue layer with peewee may be broken since some peewee internals changes! Which peewee version are you using?

It worked with UUIDs up to 2.3.2.

**Comment by captaingarbonza** [comment]
Hi @rudyryk, thanks for the quick reply! We are using peewee version 2.6.3

**Comment by rudyryk** [comment]
@captaingarbonza I'll take a look in soon :) Unfortunately, some things could not be done via peewee documented API and in some cases we need to rely on internals.

I'll review what is changed in peewee and may be have some idea to make it glue layer more robust, this is actually major #1 issue.

**Comment by rudyryk** [comment]
Should work now :) I've also just released updated 0.3 version.
