### ISSUE TITLE
Compatibility with peewee 3.0

### ISSUE THREAD

**Issue by kramarz** [05bit/peewee-async#78]
There are some features I wanted to use in 3.0a branch, but It is not compatible with peewee-async. Can it be supported?

**Comment by PatTheMav** [comment]
Second this - I've "blindly" updated my packages and peewee was updated to 3.0 and by the looks of it the whole result handling has changed and isn't compatible with async-peewee anymore.. 😕

**Comment by ssjunior** [comment]
+1

**Comment by pikeas** [comment]
Are there plans to update peewee-async to be compatible with peewee version 3?

**Comment by rudyryk** [comment]
@pikeas It would be great but currently I don't have time for this unfortunately.

**Comment by PatTheMav** [comment]
So I've tried to make sense of the breaking changes today and apart from simple changes to overall Peewee usage (API and name changes), the biggest one seems Peewee's move away from result wrappers (via `get_result_wrapper`) to using cursor wrappers.

Maybe adapting `AsyncQueryWrapper` and `AsyncRawQueryWrapper` to the new logic might already be enough. Did anyone look into this yet?

**Comment by arnulfojr** [comment]
Hello! Just a quick question about the compatibility of this library with peewee 3.0
So the current tag is a pre-release, are there any plans for making it stable?
And if you know, how reliable is the pre-release so far?

(Dont want to create another issue to discuss this repeated topic, just would be cool to have an update on this matter)

**Comment by rudyryk** [comment]
@arnulfojr Hello, just use exact version identifier with 'a' suffix: `peewee_async==0.6.0a`
