### ISSUE TITLE
MySQL support 

### ISSUE THREAD

**Issue by rudyryk** [05bit/peewee-async#8]
asyncio powered library for MySQL is available https://github.com/aio-libs/aiomysql

**Comment by Gr1N** [comment]
Hi all, any updates or news?

**Comment by rudyryk** [comment]
Hi, @Gr1N! Unfortunately didn't have time even to approach that yet.

**Comment by rudyryk** [comment]
@Gr1N I've added support for MySQL, watch for the master branch. I need to update documentation before releasing it to PyPi, I hope to do it soon :)

**Comment by Gr1N** [comment]
Nice, thnx!

**Comment by rudyryk** [comment]
Docs are updated, just published v0.5!
