### ISSUE TITLE
Unable to make use of atomic requests in tests

### ISSUE THREAD

**Issue by cburger** [05bit/peewee-async#81]
I have been trying to get a test setup working, similar to the way Django will wrap every test in an atomic transaction in order to do a rollback after the test has finished.

Everything seems to work fine if I only have one test, but the moment I add a second one I get the following error.

```
self = <peewee_async.transaction object at 0x10a6e5668>

    @asyncio.coroutine
    def __aenter__(self):
        if not asyncio.Task.current_task(loop=self.loop):
>           raise RuntimeError("The transaction must run within a task")
E           RuntimeError: The transaction must run within a task

venv/lib/python3.6/site-packages/peewee_async.py:1436: RuntimeError
```
I am unable to figure out why this is happening and what I am doing wrong. I have created a test project. Any guidance would be greatly appreciated.

https://github.com/cburger/peewee-async-test

**Comment by yarbshk** [comment]
I have a similar problem but unfortunately no one error appears eventually tests are frozen (looks like infinite execution, see more [here](https://stackoverflow.com/questions/49677670/how-to-create-transactional-fixture-with-peewee-async-and-pytest)):
```python

@pytest.fixture
async def transactional(objects):
    async with objects.transaction() as trx:
        yield
        await trx.rollback(False)
```

How can we run the tests with `peewee_async` and `pytest`?

**Comment by rudyryk** [comment]
Async transaction must be executed from asyncio task. Try to wrap coroutine with `loop.create_task()`

**Comment by cburger** [comment]
@rudyryk Is this not what `run_until_complete` does?

**Comment by rudyryk** [comment]
```python
import asyncio

async def test_task(loop=None):
    task = asyncio.Task.current_task(loop=loop)
    print("Current task:", id(task))
    asyncio.sleep(1.0, loop=loop)


if __name__ == '__main__':
    loop = asyncio.new_event_loop()
    loop.run_until_complete(test_task(loop=loop))
```

Outputs:

```bash
$ python aiotest.py 
Current task: <Task pending coro=<test_task() running at aiotest.py:5> ...
```

So yes, `run_until_complete ` should create task. Not sure how it will play with `pytest`.

I bet that tests and manager use different loops.

This is very common reason of bugs with asyncio development.

**Comment by rudyryk** [comment]
So here:

```python
loop = setup_test_loop()
app = loop.run_until_complete(get_application())
```

Did you ensure that `app.loop` and `loop` are the same?

**Comment by cburger** [comment]
@rudyryk Seems like they are not the same:

```
@pytest.fixture(scope="session", autouse=True)
def setup_database(request):
    loop = setup_test_loop()
    app = loop.run_until_complete(get_application())
>       assert loop == app.loop
E       assert <_UnixSelectorEventLoop running=False closed=False debug=False> == None
E        +  where None = <Application 0x1020586d8>.loop
```
Will investigate why it is not the same.

**Comment by cburger** [comment]
My solution was to set up the database for each test method. You can see the commit[ here](https://github.com/cburger/peewee-async-test/commit/f90103d0331acc9edd4d2e4c8c1f13e8d14d84b9).
