### ISSUE TITLE
 module 'peewee' has no attribute 'RESULTS_NAIVE'

### ISSUE THREAD

**Issue by dangerousfeng** [05bit/peewee-async#88]
when run in docker ,i receive the error;

**Comment by ahopkins** [comment]
Same.

**Comment by rudyryk** [comment]
Probably #78 ?

**Comment by ahopkins** [comment]
@rudyryk Looks like it.

**Comment by PatTheMav** [comment]
Yeah that's exactly the "result handling" issues I mentioned it my comment. I've adjusted my requirements file accordingly for the time being, as I haven't had time to work on a PR or anything to fix this. 😕

**Comment by dangerousfeng** [comment]
Thank you very much.  I've dealt with it already. Replace 3.* with peewee==2.10.2
