### ISSUE TITLE
Using get_or_create gets you a ProgrammingError

### ISSUE THREAD

**Issue by jonathan-s** [05bit/peewee-async#89]
I reported the error in https://github.com/coleifer/peewee/issues/1533 But I actually think it's an issue with peewee-async. More precisely it seems to be an issue with the following line: https://github.com/05bit/peewee-async/blame/master/peewee_async.py#L162 

When I remove `list(args)` it works appropriately.

**Comment by rudyryk** [comment]
Hi @jonathan-s! Could you please provide more complete example? We have tests for `get_or_create()` and they are passing without issues.
