### ISSUE TITLE
Sync Query is Not Allowed with manager.get

### ISSUE THREAD

**Issue by GoodiesHQ** [05bit/peewee-async#93]
I'm having a strange issue when I use `manager.get`.  
```

db = peewee_async.PooledPostgresqlDatabase("test")
db.set_allow_sync(logging.ERROR)
manager = peewee_async.Manager(db)

async def main():
    role = await manager.create(models.Roles, name="Internal", color=Color(0x11, 0x22, 0x33).val)
    print("New role created with id", role.id)
    containers = []
    for i in range(3):
        name = "Container" + str(i+1)
        cont = await manager.create(models.Containers, name=name, role_id=role.id)
        print("Container '{}' created with id {}".format(name, cont.id))
        containers.append(cont)
    cont1 = containers[0]
    r = await manager.get(models.Roles, id=cont1.role_id)
    print(r.id)
```

This appears to function correctly, but I receive a logging error that tells me it uses a synchronous query:
```
New role created with id 55f86322-0439-4bc5-986e-48b32f0d3d7d
Container 'Container1' created with id b74729c5-8d31-41e5-9fa3-c5f7be625c46
Container 'Container2' created with id 493f5e65-2ad2-40d1-8d93-b8cdf419b068
Container 'Container3' created with id 91c33b15-7753-455f-9496-c104c5970602
ERROR:root:Error, sync query is not allowed: ('SELECT "t1"."id", "t1"."name", "t1"."color", "t1"."created" FROM "roles" AS t1 WHERE ("t1"."id" = %s) LIMIT 1 OFFSET 0', ['55f8632204394bc5986e48b32f0d3d7d'], True) {}
55f86322-0439-4bc5-986e-48b32f0d3d7d
```

Synchronous queries should not be used. Is it performing this synchronously? Is this simply a warning message?

**Comment by GoodiesHQ** [comment]
I found out what the issue was. I'm using a foreign key constraint and accessing the attribute performed a synchronous query. Closing.

**Comment by rudyryk** [comment]
@GoodiesHQ Yes, I was thinking about foreign keys first but didn't see anything strange in the code snippet above.

**Comment by NoirPi** [comment]
Im running into the same Problem. But i can't find out how to solve this Problem.
I've tried some joining but then i get the error that there is no Foreign key between Table a and Table a

So im searching for a simple example to solve this Problem.

**Comment by NoirPi** [comment]
Im running into the same Problem. But i can't find out how to solve this Problem.
I've tried some joining but then i get the error that there is no Foreign key between Table a and Table a

So im searching for a simple example to solve this Problem.
