### ISSUE TITLE
[QUESTION] Are there any particular reasons why swap_database feature is experimental?

### ISSUE THREAD

**Issue by jianingy** [05bit/peewee-async#99]
Hi,

We are trying to use 'swap_database' feature for using master/slave database on the fly. There is an 'experimental warning' in the code, however, we've done some tests (including concurrent tests) without any problems. Therefore, may I ask why this is an experimental feature (any considerations about peewee changes?).

P.S. We use peewee_async with Tornado 5.1

Thanks for your reply.

**Comment by jianingy** [comment]
Hi @rudyryk ! Thanks for the reply. It would be great to have a feature like `.select(using=database)`. and I think it would be even better if we have a ProxyDatabase just like peewees' but with database switching feature. Anyway, 'swap_database' works fine currently. Thanks for this great project and looking forward to the 0.6.0 release. :)

**Comment by rudyryk** [comment]
@jianingy You can try 0.6 pre-release right now, just use `--pre` flag for pip, like that `pip install --pre peewee-async`. Also specifying `peewee-async>=0.6.0a0` should also work I believe. I'm publishing it as pre-release to prevent unexpected build breaks in the meantime. :)

**Comment by kalombos** [comment]
The feature has been removed for now.
